// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brcuimgvivabdnatqead.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyY3VpbWd2aXZhYmRuYXRxZWFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzY2MDYsImV4cCI6MjA3MzYxMjYwNn0.JN5rc9rgMtJNW4FP8bNkxs_sPxGbbcdKl-nzV_bZrMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});